In [1]:
import pickle
import pandas as pd
import numpy as np

In [2]:
with open("model.pkl", "rb") as f:
    model = pickle.load(f)

In [8]:
np.random.seed(40)

# Membuat data dummy
data = {
    'Age': np.random.randint(15, 30, 49),
    'Weight': np.random.randint(15, 30, 49),
    'BloodPressureProblems': np.random.randint(0, 2, 49),  # Generate 49 random values (0 or 1)
    'AnyTransplants': np.random.randint(0, 2, 49),
    'AnyChronicDiseases': np.random.randint(0, 2, 49),
    'HistoryOfCancerInFamily': np.random.randint(0, 2, 49),
    'NumberOfMajorSurgeries': np.random.randint(0, 2, 49),
}

data = pd.DataFrame(data)

data

,Age,Weight,BloodPressureProblems,AnyTransplants,AnyChronicDiseases,HistoryOfCancerInFamily,NumberOfMajorSurgeries
0,21,27,1,0,0,1,0
1,26,29,0,1,0,0,1
2,22,22,0,1,0,1,0
3,20,24,0,1,0,0,0
4,23,26,1,0,1,1,0
5,23,18,0,0,1,0,0
6,17,25,0,1,1,1,0
7,16,17,0,1,1,1,0
8,27,17,1,0,1,1,1
9,22,27,0,1,1,0,0
10,17,20,1,1,0,0,1
11,18,15,1,1,1,1,0
12,25,16,1,1,1,0,0
13,22,22,1,1,1,1,0
14,18,27,0,1,1,1,1
15,26,24,1,1,0,1,1
16,26,18,0,0,1,0,1
17,24,26,1,0,0,1,1
18,15,23,1,1,1,0,1
19,16,28,0,1,1,1,0
20,20,20,1,1,1,1,0
21,24,29,0,1,0,0,1
22,23,24,0,0,0,1,1
23,19,18,0,1,0,1,1
24,29,25,1,0,0,1,0
25,29,17,1,0,0,1,0
26,27,21,0,0,0,0,1
27,19,24,0,1,0,1,1
28,23,24,0,1,1,0,0
29,25,18,1,0,0,1,1
30,25,20,1,1,1,0,0
31,21,19,1,1,0,1,0
32,18,20,0,0,0,1,1
33,26,20,1,1,1,0,0
34,18,27,0,0,0,0,0
35,22,25,1,1,1,1,0
36,22,23,1,1,0,0,1
37,16,15,1,0,0,1,1
38,18,16,1,1,1,0,0
39,28,16,0,1,0,0,1
40,27,19,1,0,1,0,1
41,28,23,1,1,0,1,0
42,20,24,0,1,0,0,0
43,17,17,1,1,0,1,0
44,17,29,0,1,1,1,1
45,25,20,1,0,1,1,0
46,18,29,1,0,0,1,1
47,29,22,0,0,0,1,1
48,27,23,0,1,1,0,1

In [6]:
# Hasil prediksi
predict = model.predict(data)
predict = pd.DataFrame(predict)
predict

          0
0   18960.0
1   15000.0
2   15010.0
3   15000.0
4   22520.0
5   20910.0
6   22160.0
7   22160.0
8   22100.0
9   20910.0
10  15440.0
11  22370.0
12  21660.0
13  22520.0
14  21610.0
15  15000.0
16  20640.0
17  15240.0
18  20720.0
19  22160.0
20  22370.0
21  15000.0
22  15010.0
23  15720.0
24  16090.0
25  16090.0
26  15000.0
27  15720.0
28  20910.0
29  15170.0
30  21660.0
31  18960.0
32  15240.0
33  20570.0
34  15000.0
35  22520.0
36  15000.0
37  15330.0
38  21480.0
39  15000.0
40  20520.0
41  16090.0
42  15000.0
43  16910.0
44  21610.0
45  22550.0
46  15330.0
47  15010.0
48  20620.0